### ISSUE TITLE
Cannot find module './package.json'

### ISSUE THREAD

**Issue by crisys11** [willhlaw/node-firestore-backup-restore#11]
node: v6.11.1
package version: 1.1.2

i am receiving the next message when i try to generate a backup Cannot find module './package.json'

module.js:471
    throw err;
    ^

Error: Cannot find module './package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\usuario\AppData\Roaming\npm\node_modules\firestore-backup-restore\build\index.js:47:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by willhlaw** [comment]
@crisys11, I marked this as a bug because the tool should still run even if the package.json cannot be read. However, I'm not sure why it would be failing. Can you explain quickly how you installed and ran it?

**Comment by crisys11** [comment]
thanks i only install package with npm and after try to run backup generation like guetting started guide, i also try after with yarn

**Comment by willhlaw** [comment]
@crisys11, upgrade to latest version just published, `firestore-backup-restore@1.2.2`. If it doesn't find your package.json, then the `-V` outputs an error message instead.
